CREATE TABLE IF NOT EXISTS orders (
    id BIGSERIAL PRIMARY KEY,
    customer_email VARCHAR(255),
    sender_name VARCHAR(255),
    receiver_name VARCHAR(255),
    pickup_address VARCHAR(255),
    delivery_address VARCHAR(255),
    created_at TIMESTAMP(6),
    delivery_proof_path VARCHAR(255),
    pickup_phone VARCHAR(255),
    package_length_cm DOUBLE PRECISION NOT NULL DEFAULT 0,
    package_width_cm DOUBLE PRECISION NOT NULL DEFAULT 0,
    package_height_cm DOUBLE PRECISION NOT NULL DEFAULT 0,
    package_weight_kg DOUBLE PRECISION NOT NULL DEFAULT 0,
    delivery_phone VARCHAR(255),
    pickup_date VARCHAR(255),
    pickup_time_window VARCHAR(255),
    special_instructions VARCHAR(255),
    is_fragile BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(255),
    declared_value DOUBLE PRECISION NOT NULL DEFAULT 0,
    assigned_partner_email VARCHAR(255),
    package_type VARCHAR(255),
    payment_mode VARCHAR(255),
    delivery_type VARCHAR(255),
    invoice_status VARCHAR(255),
    pickup_lat DOUBLE PRECISION,
    pickup_lng DOUBLE PRECISION,
    pickup_city VARCHAR(255),
    pickup_postal_code VARCHAR(255),
    pickup_formatted_address VARCHAR(255),
    delivery_lat DOUBLE PRECISION,
    delivery_lng DOUBLE PRECISION,
    delivery_city VARCHAR(255),
    delivery_postal_code VARCHAR(255),
    delivery_formatted_address VARCHAR(255),
    CONSTRAINT orders_status_check CHECK (status IS NULL OR status IN ('PENDING', 'PICKED_UP', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED')),
    CONSTRAINT orders_package_type_check CHECK (package_type IS NULL OR package_type IN ('BOX', 'DOCUMENT', 'ENVELOPE', 'PALLET')),
    CONSTRAINT orders_payment_mode_check CHECK (payment_mode IS NULL OR payment_mode IN ('COD', 'ONLINE')),
    CONSTRAINT orders_delivery_type_check CHECK (delivery_type IS NULL OR delivery_type IN ('STANDARD', 'EXPRESS', 'SAME_DAY')),
    CONSTRAINT orders_invoice_status_check CHECK (invoice_status IS NULL OR invoice_status IN ('PENDING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_orders_customer_email ON orders(customer_email);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_assigned_partner_email ON orders(assigned_partner_email);
